### ISSUE TITLE
Kinect header file missing

### ISSUE THREAD

**Issue by Daniel-Valentine** [ExerciseCheck/exercisecheck#2]
https://github.com/ExerciseCheck/exercisecheck/blob/519daf96342d6644ffcba371d5d184735d9a0a1e/src/kinect2.cc#L4

`src/Kinect2.cc` has a directive to include "kinect.h" which doesn't seem to be anywhere in the project.

**Comment by mingxin-zheng** [comment]
I am not definitely sure, but believe that the Kinect.h is from the Kinect SDK (link: https://www.microsoft.com/en-us/download/details.aspx?id=44561).

**Comment by saurabh21289** [comment]
Yes, this file is a part of the Kinect SDK 2.0. Once you install the SDK you may have to reboot the system (this is necessary to flush the paths)

**Comment by Daniel-Valentine** [comment]
Got it. Was having difficulties building it on my Linux box (trying the install without the SDK) but installation on Windows went without a hitch.
