### ISSUE TITLE
Figure out how to create an exercise

### ISSUE THREAD

**Issue by shreyapandit** [ExerciseCheck/exercisecheck#5]

**Comment by shreyapandit** [comment]
Hi @waterfall414 , why are the buttons to record Ref exercises hidden through css in current codebase?

**Comment by saurabh21289** [comment]
@shreyapandit I'm not sure if you've found an answer to this, but in the current design, buttons appear and disappear from the UI as the user clicks on them step-by-step. That's why certain buttons might be hidden by default and then appear after certain button presses.

**Comment by shreyapandit** [comment]
Thanks @saurabh21289 ! Closing this
